production:
  domain: "deploy@utmsigep.org"
  deploy_to: "/sites/sigep_wp/wp-content/themes/utmsigep-wp-theme"
  repository: "https://github.com/utmsigep/utmsigep-wp-theme.git"
  branch: "master"

staging:
  domain: "deploy@sigeptnkappa.org"
  deploy_to: "/sites/sigep_wp_dev/wp-content/themes/utmsigep-wp-theme"
  repository: "https://github.com/utmsigep/utmsigep-wp-theme.git"
  branch: "master"
